// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transmite.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transmite_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transmite_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "base.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transmite_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transmite_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transmite_2eproto;
namespace im {
class GetTransmitTargetRsp;
class GetTransmitTargetRspDefaultTypeInternal;
extern GetTransmitTargetRspDefaultTypeInternal _GetTransmitTargetRsp_default_instance_;
class NewMessageReq;
class NewMessageReqDefaultTypeInternal;
extern NewMessageReqDefaultTypeInternal _NewMessageReq_default_instance_;
class NewMessageRsp;
class NewMessageRspDefaultTypeInternal;
extern NewMessageRspDefaultTypeInternal _NewMessageRsp_default_instance_;
}  // namespace im
PROTOBUF_NAMESPACE_OPEN
template<> ::im::GetTransmitTargetRsp* Arena::CreateMaybeMessage<::im::GetTransmitTargetRsp>(Arena*);
template<> ::im::NewMessageReq* Arena::CreateMaybeMessage<::im::NewMessageReq>(Arena*);
template<> ::im::NewMessageRsp* Arena::CreateMaybeMessage<::im::NewMessageRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace im {

// ===================================================================

class NewMessageReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im.NewMessageReq) */ {
 public:
  inline NewMessageReq() : NewMessageReq(nullptr) {}
  virtual ~NewMessageReq();

  NewMessageReq(const NewMessageReq& from);
  NewMessageReq(NewMessageReq&& from) noexcept
    : NewMessageReq() {
    *this = ::std::move(from);
  }

  inline NewMessageReq& operator=(const NewMessageReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewMessageReq& operator=(NewMessageReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NewMessageReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NewMessageReq* internal_default_instance() {
    return reinterpret_cast<const NewMessageReq*>(
               &_NewMessageReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NewMessageReq& a, NewMessageReq& b) {
    a.Swap(&b);
  }
  inline void Swap(NewMessageReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewMessageReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NewMessageReq* New() const final {
    return CreateMaybeMessage<NewMessageReq>(nullptr);
  }

  NewMessageReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NewMessageReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NewMessageReq& from);
  void MergeFrom(const NewMessageReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewMessageReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im.NewMessageReq";
  }
  protected:
  explicit NewMessageReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_transmite_2eproto);
    return ::descriptor_table_transmite_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestIdFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kSessionIdFieldNumber = 3,
    kChatSessionIdFieldNumber = 4,
    kMessageFieldNumber = 5,
  };
  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  void set_request_id(const std::string& value);
  void set_request_id(std::string&& value);
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  std::string* mutable_request_id();
  std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // string user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  const std::string& user_id() const;
  void set_user_id(const std::string& value);
  void set_user_id(std::string&& value);
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  std::string* mutable_user_id();
  std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string session_id = 3;
  bool has_session_id() const;
  private:
  bool _internal_has_session_id() const;
  public:
  void clear_session_id();
  const std::string& session_id() const;
  void set_session_id(const std::string& value);
  void set_session_id(std::string&& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  std::string* mutable_session_id();
  std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // string chat_session_id = 4;
  void clear_chat_session_id();
  const std::string& chat_session_id() const;
  void set_chat_session_id(const std::string& value);
  void set_chat_session_id(std::string&& value);
  void set_chat_session_id(const char* value);
  void set_chat_session_id(const char* value, size_t size);
  std::string* mutable_chat_session_id();
  std::string* release_chat_session_id();
  void set_allocated_chat_session_id(std::string* chat_session_id);
  private:
  const std::string& _internal_chat_session_id() const;
  void _internal_set_chat_session_id(const std::string& value);
  std::string* _internal_mutable_chat_session_id();
  public:

  // .im.MessageContent message = 5;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const ::im::MessageContent& message() const;
  ::im::MessageContent* release_message();
  ::im::MessageContent* mutable_message();
  void set_allocated_message(::im::MessageContent* message);
  private:
  const ::im::MessageContent& _internal_message() const;
  ::im::MessageContent* _internal_mutable_message();
  public:
  void unsafe_arena_set_allocated_message(
      ::im::MessageContent* message);
  ::im::MessageContent* unsafe_arena_release_message();

  // @@protoc_insertion_point(class_scope:im.NewMessageReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chat_session_id_;
  ::im::MessageContent* message_;
  friend struct ::TableStruct_transmite_2eproto;
};
// -------------------------------------------------------------------

class NewMessageRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im.NewMessageRsp) */ {
 public:
  inline NewMessageRsp() : NewMessageRsp(nullptr) {}
  virtual ~NewMessageRsp();

  NewMessageRsp(const NewMessageRsp& from);
  NewMessageRsp(NewMessageRsp&& from) noexcept
    : NewMessageRsp() {
    *this = ::std::move(from);
  }

  inline NewMessageRsp& operator=(const NewMessageRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline NewMessageRsp& operator=(NewMessageRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NewMessageRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NewMessageRsp* internal_default_instance() {
    return reinterpret_cast<const NewMessageRsp*>(
               &_NewMessageRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NewMessageRsp& a, NewMessageRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(NewMessageRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NewMessageRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NewMessageRsp* New() const final {
    return CreateMaybeMessage<NewMessageRsp>(nullptr);
  }

  NewMessageRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NewMessageRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NewMessageRsp& from);
  void MergeFrom(const NewMessageRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NewMessageRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im.NewMessageRsp";
  }
  protected:
  explicit NewMessageRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_transmite_2eproto);
    return ::descriptor_table_transmite_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestIdFieldNumber = 1,
    kErrmsgFieldNumber = 3,
    kSuccessFieldNumber = 2,
  };
  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  void set_request_id(const std::string& value);
  void set_request_id(std::string&& value);
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  std::string* mutable_request_id();
  std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:im.NewMessageRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transmite_2eproto;
};
// -------------------------------------------------------------------

class GetTransmitTargetRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:im.GetTransmitTargetRsp) */ {
 public:
  inline GetTransmitTargetRsp() : GetTransmitTargetRsp(nullptr) {}
  virtual ~GetTransmitTargetRsp();

  GetTransmitTargetRsp(const GetTransmitTargetRsp& from);
  GetTransmitTargetRsp(GetTransmitTargetRsp&& from) noexcept
    : GetTransmitTargetRsp() {
    *this = ::std::move(from);
  }

  inline GetTransmitTargetRsp& operator=(const GetTransmitTargetRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetTransmitTargetRsp& operator=(GetTransmitTargetRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetTransmitTargetRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetTransmitTargetRsp* internal_default_instance() {
    return reinterpret_cast<const GetTransmitTargetRsp*>(
               &_GetTransmitTargetRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetTransmitTargetRsp& a, GetTransmitTargetRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(GetTransmitTargetRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetTransmitTargetRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetTransmitTargetRsp* New() const final {
    return CreateMaybeMessage<GetTransmitTargetRsp>(nullptr);
  }

  GetTransmitTargetRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetTransmitTargetRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetTransmitTargetRsp& from);
  void MergeFrom(const GetTransmitTargetRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetTransmitTargetRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "im.GetTransmitTargetRsp";
  }
  protected:
  explicit GetTransmitTargetRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_transmite_2eproto);
    return ::descriptor_table_transmite_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetIdListFieldNumber = 5,
    kRequestIdFieldNumber = 1,
    kErrmsgFieldNumber = 3,
    kMessageFieldNumber = 4,
    kSuccessFieldNumber = 2,
  };
  // repeated string target_id_list = 5;
  int target_id_list_size() const;
  private:
  int _internal_target_id_list_size() const;
  public:
  void clear_target_id_list();
  const std::string& target_id_list(int index) const;
  std::string* mutable_target_id_list(int index);
  void set_target_id_list(int index, const std::string& value);
  void set_target_id_list(int index, std::string&& value);
  void set_target_id_list(int index, const char* value);
  void set_target_id_list(int index, const char* value, size_t size);
  std::string* add_target_id_list();
  void add_target_id_list(const std::string& value);
  void add_target_id_list(std::string&& value);
  void add_target_id_list(const char* value);
  void add_target_id_list(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& target_id_list() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_target_id_list();
  private:
  const std::string& _internal_target_id_list(int index) const;
  std::string* _internal_add_target_id_list();
  public:

  // string request_id = 1;
  void clear_request_id();
  const std::string& request_id() const;
  void set_request_id(const std::string& value);
  void set_request_id(std::string&& value);
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  std::string* mutable_request_id();
  std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // .im.MessageInfo message = 4;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const ::im::MessageInfo& message() const;
  ::im::MessageInfo* release_message();
  ::im::MessageInfo* mutable_message();
  void set_allocated_message(::im::MessageInfo* message);
  private:
  const ::im::MessageInfo& _internal_message() const;
  ::im::MessageInfo* _internal_mutable_message();
  public:
  void unsafe_arena_set_allocated_message(
      ::im::MessageInfo* message);
  ::im::MessageInfo* unsafe_arena_release_message();

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:im.GetTransmitTargetRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> target_id_list_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::im::MessageInfo* message_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transmite_2eproto;
};
// ===================================================================

class MsgTransmitService_Stub;

class MsgTransmitService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline MsgTransmitService() {};
 public:
  virtual ~MsgTransmitService();

  typedef MsgTransmitService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void GetTransmitTarget(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::im::NewMessageReq* request,
                       ::im::GetTransmitTargetRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MsgTransmitService);
};

class MsgTransmitService_Stub : public MsgTransmitService {
 public:
  MsgTransmitService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  MsgTransmitService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~MsgTransmitService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements MsgTransmitService ------------------------------------------

  void GetTransmitTarget(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::im::NewMessageReq* request,
                       ::im::GetTransmitTargetRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MsgTransmitService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NewMessageReq

// string request_id = 1;
inline void NewMessageReq::clear_request_id() {
  request_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NewMessageReq::request_id() const {
  // @@protoc_insertion_point(field_get:im.NewMessageReq.request_id)
  return _internal_request_id();
}
inline void NewMessageReq::set_request_id(const std::string& value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:im.NewMessageReq.request_id)
}
inline std::string* NewMessageReq::mutable_request_id() {
  // @@protoc_insertion_point(field_mutable:im.NewMessageReq.request_id)
  return _internal_mutable_request_id();
}
inline const std::string& NewMessageReq::_internal_request_id() const {
  return request_id_.Get();
}
inline void NewMessageReq::_internal_set_request_id(const std::string& value) {
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NewMessageReq::set_request_id(std::string&& value) {
  
  request_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.NewMessageReq.request_id)
}
inline void NewMessageReq::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.NewMessageReq.request_id)
}
inline void NewMessageReq::set_request_id(const char* value,
    size_t size) {
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.NewMessageReq.request_id)
}
inline std::string* NewMessageReq::_internal_mutable_request_id() {
  
  return request_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NewMessageReq::release_request_id() {
  // @@protoc_insertion_point(field_release:im.NewMessageReq.request_id)
  return request_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NewMessageReq::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  request_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), request_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.NewMessageReq.request_id)
}

// string user_id = 2;
inline bool NewMessageReq::_internal_has_user_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NewMessageReq::has_user_id() const {
  return _internal_has_user_id();
}
inline void NewMessageReq::clear_user_id() {
  user_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& NewMessageReq::user_id() const {
  // @@protoc_insertion_point(field_get:im.NewMessageReq.user_id)
  return _internal_user_id();
}
inline void NewMessageReq::set_user_id(const std::string& value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:im.NewMessageReq.user_id)
}
inline std::string* NewMessageReq::mutable_user_id() {
  // @@protoc_insertion_point(field_mutable:im.NewMessageReq.user_id)
  return _internal_mutable_user_id();
}
inline const std::string& NewMessageReq::_internal_user_id() const {
  return user_id_.Get();
}
inline void NewMessageReq::_internal_set_user_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NewMessageReq::set_user_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  user_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.NewMessageReq.user_id)
}
inline void NewMessageReq::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.NewMessageReq.user_id)
}
inline void NewMessageReq::set_user_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  user_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.NewMessageReq.user_id)
}
inline std::string* NewMessageReq::_internal_mutable_user_id() {
  _has_bits_[0] |= 0x00000001u;
  return user_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NewMessageReq::release_user_id() {
  // @@protoc_insertion_point(field_release:im.NewMessageReq.user_id)
  if (!_internal_has_user_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return user_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NewMessageReq::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.NewMessageReq.user_id)
}

// string session_id = 3;
inline bool NewMessageReq::_internal_has_session_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool NewMessageReq::has_session_id() const {
  return _internal_has_session_id();
}
inline void NewMessageReq::clear_session_id() {
  session_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& NewMessageReq::session_id() const {
  // @@protoc_insertion_point(field_get:im.NewMessageReq.session_id)
  return _internal_session_id();
}
inline void NewMessageReq::set_session_id(const std::string& value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:im.NewMessageReq.session_id)
}
inline std::string* NewMessageReq::mutable_session_id() {
  // @@protoc_insertion_point(field_mutable:im.NewMessageReq.session_id)
  return _internal_mutable_session_id();
}
inline const std::string& NewMessageReq::_internal_session_id() const {
  return session_id_.Get();
}
inline void NewMessageReq::_internal_set_session_id(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NewMessageReq::set_session_id(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  session_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.NewMessageReq.session_id)
}
inline void NewMessageReq::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.NewMessageReq.session_id)
}
inline void NewMessageReq::set_session_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.NewMessageReq.session_id)
}
inline std::string* NewMessageReq::_internal_mutable_session_id() {
  _has_bits_[0] |= 0x00000002u;
  return session_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NewMessageReq::release_session_id() {
  // @@protoc_insertion_point(field_release:im.NewMessageReq.session_id)
  if (!_internal_has_session_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return session_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NewMessageReq::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  session_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.NewMessageReq.session_id)
}

// string chat_session_id = 4;
inline void NewMessageReq::clear_chat_session_id() {
  chat_session_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NewMessageReq::chat_session_id() const {
  // @@protoc_insertion_point(field_get:im.NewMessageReq.chat_session_id)
  return _internal_chat_session_id();
}
inline void NewMessageReq::set_chat_session_id(const std::string& value) {
  _internal_set_chat_session_id(value);
  // @@protoc_insertion_point(field_set:im.NewMessageReq.chat_session_id)
}
inline std::string* NewMessageReq::mutable_chat_session_id() {
  // @@protoc_insertion_point(field_mutable:im.NewMessageReq.chat_session_id)
  return _internal_mutable_chat_session_id();
}
inline const std::string& NewMessageReq::_internal_chat_session_id() const {
  return chat_session_id_.Get();
}
inline void NewMessageReq::_internal_set_chat_session_id(const std::string& value) {
  
  chat_session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NewMessageReq::set_chat_session_id(std::string&& value) {
  
  chat_session_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.NewMessageReq.chat_session_id)
}
inline void NewMessageReq::set_chat_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  chat_session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.NewMessageReq.chat_session_id)
}
inline void NewMessageReq::set_chat_session_id(const char* value,
    size_t size) {
  
  chat_session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.NewMessageReq.chat_session_id)
}
inline std::string* NewMessageReq::_internal_mutable_chat_session_id() {
  
  return chat_session_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NewMessageReq::release_chat_session_id() {
  // @@protoc_insertion_point(field_release:im.NewMessageReq.chat_session_id)
  return chat_session_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NewMessageReq::set_allocated_chat_session_id(std::string* chat_session_id) {
  if (chat_session_id != nullptr) {
    
  } else {
    
  }
  chat_session_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), chat_session_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.NewMessageReq.chat_session_id)
}

// .im.MessageContent message = 5;
inline bool NewMessageReq::_internal_has_message() const {
  return this != internal_default_instance() && message_ != nullptr;
}
inline bool NewMessageReq::has_message() const {
  return _internal_has_message();
}
inline const ::im::MessageContent& NewMessageReq::_internal_message() const {
  const ::im::MessageContent* p = message_;
  return p != nullptr ? *p : *reinterpret_cast<const ::im::MessageContent*>(
      &::im::_MessageContent_default_instance_);
}
inline const ::im::MessageContent& NewMessageReq::message() const {
  // @@protoc_insertion_point(field_get:im.NewMessageReq.message)
  return _internal_message();
}
inline void NewMessageReq::unsafe_arena_set_allocated_message(
    ::im::MessageContent* message) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(message_);
  }
  message_ = message;
  if (message) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:im.NewMessageReq.message)
}
inline ::im::MessageContent* NewMessageReq::release_message() {
  
  ::im::MessageContent* temp = message_;
  message_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::im::MessageContent* NewMessageReq::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_release:im.NewMessageReq.message)
  
  ::im::MessageContent* temp = message_;
  message_ = nullptr;
  return temp;
}
inline ::im::MessageContent* NewMessageReq::_internal_mutable_message() {
  
  if (message_ == nullptr) {
    auto* p = CreateMaybeMessage<::im::MessageContent>(GetArena());
    message_ = p;
  }
  return message_;
}
inline ::im::MessageContent* NewMessageReq::mutable_message() {
  // @@protoc_insertion_point(field_mutable:im.NewMessageReq.message)
  return _internal_mutable_message();
}
inline void NewMessageReq::set_allocated_message(::im::MessageContent* message) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(message_);
  }
  if (message) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(message)->GetArena();
    if (message_arena != submessage_arena) {
      message = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, message, submessage_arena);
    }
    
  } else {
    
  }
  message_ = message;
  // @@protoc_insertion_point(field_set_allocated:im.NewMessageReq.message)
}

// -------------------------------------------------------------------

// NewMessageRsp

// string request_id = 1;
inline void NewMessageRsp::clear_request_id() {
  request_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NewMessageRsp::request_id() const {
  // @@protoc_insertion_point(field_get:im.NewMessageRsp.request_id)
  return _internal_request_id();
}
inline void NewMessageRsp::set_request_id(const std::string& value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:im.NewMessageRsp.request_id)
}
inline std::string* NewMessageRsp::mutable_request_id() {
  // @@protoc_insertion_point(field_mutable:im.NewMessageRsp.request_id)
  return _internal_mutable_request_id();
}
inline const std::string& NewMessageRsp::_internal_request_id() const {
  return request_id_.Get();
}
inline void NewMessageRsp::_internal_set_request_id(const std::string& value) {
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NewMessageRsp::set_request_id(std::string&& value) {
  
  request_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.NewMessageRsp.request_id)
}
inline void NewMessageRsp::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.NewMessageRsp.request_id)
}
inline void NewMessageRsp::set_request_id(const char* value,
    size_t size) {
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.NewMessageRsp.request_id)
}
inline std::string* NewMessageRsp::_internal_mutable_request_id() {
  
  return request_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NewMessageRsp::release_request_id() {
  // @@protoc_insertion_point(field_release:im.NewMessageRsp.request_id)
  return request_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NewMessageRsp::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  request_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), request_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.NewMessageRsp.request_id)
}

// bool success = 2;
inline void NewMessageRsp::clear_success() {
  success_ = false;
}
inline bool NewMessageRsp::_internal_success() const {
  return success_;
}
inline bool NewMessageRsp::success() const {
  // @@protoc_insertion_point(field_get:im.NewMessageRsp.success)
  return _internal_success();
}
inline void NewMessageRsp::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void NewMessageRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:im.NewMessageRsp.success)
}

// string errmsg = 3;
inline void NewMessageRsp::clear_errmsg() {
  errmsg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& NewMessageRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:im.NewMessageRsp.errmsg)
  return _internal_errmsg();
}
inline void NewMessageRsp::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:im.NewMessageRsp.errmsg)
}
inline std::string* NewMessageRsp::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:im.NewMessageRsp.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& NewMessageRsp::_internal_errmsg() const {
  return errmsg_.Get();
}
inline void NewMessageRsp::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void NewMessageRsp::set_errmsg(std::string&& value) {
  
  errmsg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.NewMessageRsp.errmsg)
}
inline void NewMessageRsp::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.NewMessageRsp.errmsg)
}
inline void NewMessageRsp::set_errmsg(const char* value,
    size_t size) {
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.NewMessageRsp.errmsg)
}
inline std::string* NewMessageRsp::_internal_mutable_errmsg() {
  
  return errmsg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* NewMessageRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:im.NewMessageRsp.errmsg)
  return errmsg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void NewMessageRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.NewMessageRsp.errmsg)
}

// -------------------------------------------------------------------

// GetTransmitTargetRsp

// string request_id = 1;
inline void GetTransmitTargetRsp::clear_request_id() {
  request_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GetTransmitTargetRsp::request_id() const {
  // @@protoc_insertion_point(field_get:im.GetTransmitTargetRsp.request_id)
  return _internal_request_id();
}
inline void GetTransmitTargetRsp::set_request_id(const std::string& value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:im.GetTransmitTargetRsp.request_id)
}
inline std::string* GetTransmitTargetRsp::mutable_request_id() {
  // @@protoc_insertion_point(field_mutable:im.GetTransmitTargetRsp.request_id)
  return _internal_mutable_request_id();
}
inline const std::string& GetTransmitTargetRsp::_internal_request_id() const {
  return request_id_.Get();
}
inline void GetTransmitTargetRsp::_internal_set_request_id(const std::string& value) {
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GetTransmitTargetRsp::set_request_id(std::string&& value) {
  
  request_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.GetTransmitTargetRsp.request_id)
}
inline void GetTransmitTargetRsp::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.GetTransmitTargetRsp.request_id)
}
inline void GetTransmitTargetRsp::set_request_id(const char* value,
    size_t size) {
  
  request_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.GetTransmitTargetRsp.request_id)
}
inline std::string* GetTransmitTargetRsp::_internal_mutable_request_id() {
  
  return request_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GetTransmitTargetRsp::release_request_id() {
  // @@protoc_insertion_point(field_release:im.GetTransmitTargetRsp.request_id)
  return request_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GetTransmitTargetRsp::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  request_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), request_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.GetTransmitTargetRsp.request_id)
}

// bool success = 2;
inline void GetTransmitTargetRsp::clear_success() {
  success_ = false;
}
inline bool GetTransmitTargetRsp::_internal_success() const {
  return success_;
}
inline bool GetTransmitTargetRsp::success() const {
  // @@protoc_insertion_point(field_get:im.GetTransmitTargetRsp.success)
  return _internal_success();
}
inline void GetTransmitTargetRsp::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void GetTransmitTargetRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:im.GetTransmitTargetRsp.success)
}

// string errmsg = 3;
inline void GetTransmitTargetRsp::clear_errmsg() {
  errmsg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GetTransmitTargetRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:im.GetTransmitTargetRsp.errmsg)
  return _internal_errmsg();
}
inline void GetTransmitTargetRsp::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:im.GetTransmitTargetRsp.errmsg)
}
inline std::string* GetTransmitTargetRsp::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:im.GetTransmitTargetRsp.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& GetTransmitTargetRsp::_internal_errmsg() const {
  return errmsg_.Get();
}
inline void GetTransmitTargetRsp::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GetTransmitTargetRsp::set_errmsg(std::string&& value) {
  
  errmsg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:im.GetTransmitTargetRsp.errmsg)
}
inline void GetTransmitTargetRsp::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:im.GetTransmitTargetRsp.errmsg)
}
inline void GetTransmitTargetRsp::set_errmsg(const char* value,
    size_t size) {
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:im.GetTransmitTargetRsp.errmsg)
}
inline std::string* GetTransmitTargetRsp::_internal_mutable_errmsg() {
  
  return errmsg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GetTransmitTargetRsp::release_errmsg() {
  // @@protoc_insertion_point(field_release:im.GetTransmitTargetRsp.errmsg)
  return errmsg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GetTransmitTargetRsp::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:im.GetTransmitTargetRsp.errmsg)
}

// .im.MessageInfo message = 4;
inline bool GetTransmitTargetRsp::_internal_has_message() const {
  return this != internal_default_instance() && message_ != nullptr;
}
inline bool GetTransmitTargetRsp::has_message() const {
  return _internal_has_message();
}
inline const ::im::MessageInfo& GetTransmitTargetRsp::_internal_message() const {
  const ::im::MessageInfo* p = message_;
  return p != nullptr ? *p : *reinterpret_cast<const ::im::MessageInfo*>(
      &::im::_MessageInfo_default_instance_);
}
inline const ::im::MessageInfo& GetTransmitTargetRsp::message() const {
  // @@protoc_insertion_point(field_get:im.GetTransmitTargetRsp.message)
  return _internal_message();
}
inline void GetTransmitTargetRsp::unsafe_arena_set_allocated_message(
    ::im::MessageInfo* message) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(message_);
  }
  message_ = message;
  if (message) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:im.GetTransmitTargetRsp.message)
}
inline ::im::MessageInfo* GetTransmitTargetRsp::release_message() {
  
  ::im::MessageInfo* temp = message_;
  message_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::im::MessageInfo* GetTransmitTargetRsp::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_release:im.GetTransmitTargetRsp.message)
  
  ::im::MessageInfo* temp = message_;
  message_ = nullptr;
  return temp;
}
inline ::im::MessageInfo* GetTransmitTargetRsp::_internal_mutable_message() {
  
  if (message_ == nullptr) {
    auto* p = CreateMaybeMessage<::im::MessageInfo>(GetArena());
    message_ = p;
  }
  return message_;
}
inline ::im::MessageInfo* GetTransmitTargetRsp::mutable_message() {
  // @@protoc_insertion_point(field_mutable:im.GetTransmitTargetRsp.message)
  return _internal_mutable_message();
}
inline void GetTransmitTargetRsp::set_allocated_message(::im::MessageInfo* message) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(message_);
  }
  if (message) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(message)->GetArena();
    if (message_arena != submessage_arena) {
      message = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, message, submessage_arena);
    }
    
  } else {
    
  }
  message_ = message;
  // @@protoc_insertion_point(field_set_allocated:im.GetTransmitTargetRsp.message)
}

// repeated string target_id_list = 5;
inline int GetTransmitTargetRsp::_internal_target_id_list_size() const {
  return target_id_list_.size();
}
inline int GetTransmitTargetRsp::target_id_list_size() const {
  return _internal_target_id_list_size();
}
inline void GetTransmitTargetRsp::clear_target_id_list() {
  target_id_list_.Clear();
}
inline std::string* GetTransmitTargetRsp::add_target_id_list() {
  // @@protoc_insertion_point(field_add_mutable:im.GetTransmitTargetRsp.target_id_list)
  return _internal_add_target_id_list();
}
inline const std::string& GetTransmitTargetRsp::_internal_target_id_list(int index) const {
  return target_id_list_.Get(index);
}
inline const std::string& GetTransmitTargetRsp::target_id_list(int index) const {
  // @@protoc_insertion_point(field_get:im.GetTransmitTargetRsp.target_id_list)
  return _internal_target_id_list(index);
}
inline std::string* GetTransmitTargetRsp::mutable_target_id_list(int index) {
  // @@protoc_insertion_point(field_mutable:im.GetTransmitTargetRsp.target_id_list)
  return target_id_list_.Mutable(index);
}
inline void GetTransmitTargetRsp::set_target_id_list(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:im.GetTransmitTargetRsp.target_id_list)
  target_id_list_.Mutable(index)->assign(value);
}
inline void GetTransmitTargetRsp::set_target_id_list(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:im.GetTransmitTargetRsp.target_id_list)
  target_id_list_.Mutable(index)->assign(std::move(value));
}
inline void GetTransmitTargetRsp::set_target_id_list(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  target_id_list_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:im.GetTransmitTargetRsp.target_id_list)
}
inline void GetTransmitTargetRsp::set_target_id_list(int index, const char* value, size_t size) {
  target_id_list_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:im.GetTransmitTargetRsp.target_id_list)
}
inline std::string* GetTransmitTargetRsp::_internal_add_target_id_list() {
  return target_id_list_.Add();
}
inline void GetTransmitTargetRsp::add_target_id_list(const std::string& value) {
  target_id_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:im.GetTransmitTargetRsp.target_id_list)
}
inline void GetTransmitTargetRsp::add_target_id_list(std::string&& value) {
  target_id_list_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:im.GetTransmitTargetRsp.target_id_list)
}
inline void GetTransmitTargetRsp::add_target_id_list(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  target_id_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:im.GetTransmitTargetRsp.target_id_list)
}
inline void GetTransmitTargetRsp::add_target_id_list(const char* value, size_t size) {
  target_id_list_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:im.GetTransmitTargetRsp.target_id_list)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetTransmitTargetRsp::target_id_list() const {
  // @@protoc_insertion_point(field_list:im.GetTransmitTargetRsp.target_id_list)
  return target_id_list_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetTransmitTargetRsp::mutable_target_id_list() {
  // @@protoc_insertion_point(field_mutable_list:im.GetTransmitTargetRsp.target_id_list)
  return &target_id_list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace im

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transmite_2eproto
